# Generated by Django 4.1 on 2022-08-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decade',
            name='photo_url',
        ),
    ]
